--------------------------------------------------------
--  文件已创建 - 星期日-七月-16-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table AUTHUSER
--------------------------------------------------------

  CREATE TABLE "RSDL"."AUTHUSER" 
   (	"USER_ID" NUMBER(19,0), 
	"BIRTHDAY" DATE, 
	"CREATE_TIME" TIMESTAMP (6), 
	"PASSWORD" VARCHAR2(255 CHAR), 
	"STATUS" NUMBER(10,0), 
	"USER_NAME" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table AUTH_MENU
--------------------------------------------------------

  CREATE TABLE "RSDL"."AUTH_MENU" 
   (	"MENU_ID" NUMBER(19,0), 
	"PARENT_ID" NUMBER(19,0), 
	"CODE" VARCHAR2(20 BYTE), 
	"NAME" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table AUTH_MENU_OPERATE
--------------------------------------------------------

  CREATE TABLE "RSDL"."AUTH_MENU_OPERATE" 
   (	"OPERATE_ID" NUMBER(19,0), 
	"CODE" VARCHAR2(20 BYTE), 
	"NAME" VARCHAR2(20 BYTE), 
	"MENU_ID" NUMBER(19,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table AUTH_PERMISSION
--------------------------------------------------------

  CREATE TABLE "RSDL"."AUTH_PERMISSION" 
   (	"PERMISSION_ID" NUMBER(19,0), 
	"TYPE" CHAR(1 BYTE), 
	"RESOURCE_ID" NUMBER(19,0), 
	"CODE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
 

   COMMENT ON COLUMN "RSDL"."AUTH_PERMISSION"."TYPE" IS '0表示菜单,1表示操作';
 
   COMMENT ON COLUMN "RSDL"."AUTH_PERMISSION"."RESOURCE_ID" IS '如果type是0则是菜单ID，type是1则是操作ID';
--------------------------------------------------------
--  DDL for Table AUTH_PERMISSION_GRANT
--------------------------------------------------------

  CREATE TABLE "RSDL"."AUTH_PERMISSION_GRANT" 
   (	"GRANT_ID" NUMBER(19,0), 
	"ROLE_ID" NUMBER(19,0), 
	"PERMISSION_ID" NUMBER(19,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table AUTH_ROLE
--------------------------------------------------------

  CREATE TABLE "RSDL"."AUTH_ROLE" 
   (	"ROLE_ID" NUMBER(19,0), 
	"NAME" VARCHAR2(20 BYTE), 
	"CODE" VARCHAR2(20 BYTE), 
	"DESCRIPTION" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table AUTH_USER
--------------------------------------------------------

  CREATE TABLE "RSDL"."AUTH_USER" 
   (	"USER_ID" NUMBER(19,0), 
	"USER_NAME" VARCHAR2(20 BYTE), 
	"PASSWORD" VARCHAR2(50 BYTE), 
	"STATUS" CHAR(1 BYTE), 
	"CREATE_TIME" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table AUTH_USER_ROLE
--------------------------------------------------------

  CREATE TABLE "RSDL"."AUTH_USER_ROLE" 
   (	"UR_ID" NUMBER(19,0), 
	"USER_ID" NUMBER(19,0), 
	"ROLE_ID" NUMBER(19,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DEMO
--------------------------------------------------------

  CREATE TABLE "RSDL"."DEMO" 
   (	"ID" NUMBER(19,0), 
	"BIRTHDAY" DATE, 
	"CREATETIME" DATE, 
	"GENDER" CHAR(1 BYTE), 
	"NAME" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into RSDL.AUTHUSER
SET DEFINE OFF;
REM INSERTING into RSDL.AUTH_MENU
SET DEFINE OFF;
REM INSERTING into RSDL.AUTH_MENU_OPERATE
SET DEFINE OFF;
REM INSERTING into RSDL.AUTH_PERMISSION
SET DEFINE OFF;
REM INSERTING into RSDL.AUTH_PERMISSION_GRANT
SET DEFINE OFF;
REM INSERTING into RSDL.AUTH_ROLE
SET DEFINE OFF;
REM INSERTING into RSDL.AUTH_USER
SET DEFINE OFF;
REM INSERTING into RSDL.AUTH_USER_ROLE
SET DEFINE OFF;
REM INSERTING into RSDL.DEMO
SET DEFINE OFF;
Insert into RSDL.DEMO (ID,BIRTHDAY,CREATETIME,GENDER,NAME) values (500100,to_date('12-7月 -17','DD-MON-RR'),to_date('14-7月 -17','DD-MON-RR'),'1','sssssss');
--------------------------------------------------------
--  DDL for Index AUTH_USER_ROLE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "RSDL"."AUTH_USER_ROLE_PK" ON "RSDL"."AUTH_USER_ROLE" ("UR_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index AUTH_MENU_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "RSDL"."AUTH_MENU_PK" ON "RSDL"."AUTH_MENU" ("MENU_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index AUTH_MENU_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "RSDL"."AUTH_MENU_UK1" ON "RSDL"."AUTH_MENU" ("CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index AUTH_PERMISSION_GRANT_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "RSDL"."AUTH_PERMISSION_GRANT_UK1" ON "RSDL"."AUTH_PERMISSION_GRANT" ("ROLE_ID", "PERMISSION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index AUTH_PERMISSION_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "RSDL"."AUTH_PERMISSION_UK1" ON "RSDL"."AUTH_PERMISSION" ("CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index AUTH_PERMISSION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "RSDL"."AUTH_PERMISSION_PK" ON "RSDL"."AUTH_PERMISSION" ("PERMISSION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index AUTH_USER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "RSDL"."AUTH_USER_PK" ON "RSDL"."AUTH_USER" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index AUTH_MENU_ACTION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "RSDL"."AUTH_MENU_ACTION_PK" ON "RSDL"."AUTH_MENU_OPERATE" ("OPERATE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index AUTH_ROLE_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "RSDL"."AUTH_ROLE_UK1" ON "RSDL"."AUTH_ROLE" ("CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index AUTH_ROLE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "RSDL"."AUTH_ROLE_PK" ON "RSDL"."AUTH_ROLE" ("ROLE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index AUTH_USER_ROLE_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "RSDL"."AUTH_USER_ROLE_UK1" ON "RSDL"."AUTH_USER_ROLE" ("USER_ID", "ROLE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index AUTH_MENU_OPERATE_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "RSDL"."AUTH_MENU_OPERATE_UK1" ON "RSDL"."AUTH_MENU_OPERATE" ("CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index AUTH_PERMISSION_GRANT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "RSDL"."AUTH_PERMISSION_GRANT_PK" ON "RSDL"."AUTH_PERMISSION_GRANT" ("GRANT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index AUTH_USER_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "RSDL"."AUTH_USER_UK1" ON "RSDL"."AUTH_USER" ("USER_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table AUTH_PERMISSION
--------------------------------------------------------

  ALTER TABLE "RSDL"."AUTH_PERMISSION" ADD CONSTRAINT "AUTH_PERMISSION_PK" PRIMARY KEY ("PERMISSION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "RSDL"."AUTH_PERMISSION" ADD CONSTRAINT "AUTH_PERMISSION_UK1" UNIQUE ("CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "RSDL"."AUTH_PERMISSION" MODIFY ("PERMISSION_ID" NOT NULL ENABLE);
 
  ALTER TABLE "RSDL"."AUTH_PERMISSION" MODIFY ("TYPE" NOT NULL ENABLE);
 
  ALTER TABLE "RSDL"."AUTH_PERMISSION" MODIFY ("RESOURCE_ID" NOT NULL ENABLE);
 
  ALTER TABLE "RSDL"."AUTH_PERMISSION" MODIFY ("CODE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table AUTHUSER
--------------------------------------------------------

  ALTER TABLE "RSDL"."AUTHUSER" MODIFY ("USER_ID" NOT NULL ENABLE);
 
  ALTER TABLE "RSDL"."AUTHUSER" ADD PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table AUTH_ROLE
--------------------------------------------------------

  ALTER TABLE "RSDL"."AUTH_ROLE" ADD CONSTRAINT "AUTH_ROLE_PK" PRIMARY KEY ("ROLE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "RSDL"."AUTH_ROLE" ADD CONSTRAINT "AUTH_ROLE_UK1" UNIQUE ("CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "RSDL"."AUTH_ROLE" MODIFY ("ROLE_ID" NOT NULL ENABLE);
 
  ALTER TABLE "RSDL"."AUTH_ROLE" MODIFY ("NAME" NOT NULL ENABLE);
 
  ALTER TABLE "RSDL"."AUTH_ROLE" MODIFY ("CODE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table AUTH_MENU
--------------------------------------------------------

  ALTER TABLE "RSDL"."AUTH_MENU" ADD CONSTRAINT "AUTH_MENU_PK" PRIMARY KEY ("MENU_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "RSDL"."AUTH_MENU" ADD CONSTRAINT "AUTH_MENU_UK1" UNIQUE ("CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "RSDL"."AUTH_MENU" MODIFY ("MENU_ID" NOT NULL ENABLE);
 
  ALTER TABLE "RSDL"."AUTH_MENU" MODIFY ("CODE" NOT NULL ENABLE);
 
  ALTER TABLE "RSDL"."AUTH_MENU" MODIFY ("NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table AUTH_USER
--------------------------------------------------------

  ALTER TABLE "RSDL"."AUTH_USER" ADD CONSTRAINT "AUTH_USER_PK" PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "RSDL"."AUTH_USER" ADD CONSTRAINT "AUTH_USER_UK1" UNIQUE ("USER_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "RSDL"."AUTH_USER" MODIFY ("USER_ID" NOT NULL ENABLE);
 
  ALTER TABLE "RSDL"."AUTH_USER" MODIFY ("USER_NAME" NOT NULL ENABLE);
 
  ALTER TABLE "RSDL"."AUTH_USER" MODIFY ("STATUS" NOT NULL ENABLE);
 
  ALTER TABLE "RSDL"."AUTH_USER" MODIFY ("CREATE_TIME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DEMO
--------------------------------------------------------

  ALTER TABLE "RSDL"."DEMO" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "RSDL"."DEMO" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table AUTH_USER_ROLE
--------------------------------------------------------

  ALTER TABLE "RSDL"."AUTH_USER_ROLE" ADD CONSTRAINT "AUTH_USER_ROLE_PK" PRIMARY KEY ("UR_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "RSDL"."AUTH_USER_ROLE" ADD CONSTRAINT "AUTH_USER_ROLE_UK1" UNIQUE ("USER_ID", "ROLE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "RSDL"."AUTH_USER_ROLE" MODIFY ("UR_ID" NOT NULL ENABLE);
 
  ALTER TABLE "RSDL"."AUTH_USER_ROLE" MODIFY ("USER_ID" NOT NULL ENABLE);
 
  ALTER TABLE "RSDL"."AUTH_USER_ROLE" MODIFY ("ROLE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table AUTH_PERMISSION_GRANT
--------------------------------------------------------

  ALTER TABLE "RSDL"."AUTH_PERMISSION_GRANT" ADD CONSTRAINT "AUTH_PERMISSION_GRANT_PK" PRIMARY KEY ("GRANT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "RSDL"."AUTH_PERMISSION_GRANT" ADD CONSTRAINT "AUTH_PERMISSION_GRANT_UK1" UNIQUE ("ROLE_ID", "PERMISSION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "RSDL"."AUTH_PERMISSION_GRANT" MODIFY ("GRANT_ID" NOT NULL ENABLE);
 
  ALTER TABLE "RSDL"."AUTH_PERMISSION_GRANT" MODIFY ("ROLE_ID" NOT NULL ENABLE);
 
  ALTER TABLE "RSDL"."AUTH_PERMISSION_GRANT" MODIFY ("PERMISSION_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table AUTH_MENU_OPERATE
--------------------------------------------------------

  ALTER TABLE "RSDL"."AUTH_MENU_OPERATE" ADD CONSTRAINT "AUTH_MENU_ACTION_PK" PRIMARY KEY ("OPERATE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "RSDL"."AUTH_MENU_OPERATE" ADD CONSTRAINT "AUTH_MENU_OPERATE_UK1" UNIQUE ("CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "RSDL"."AUTH_MENU_OPERATE" MODIFY ("OPERATE_ID" NOT NULL ENABLE);
 
  ALTER TABLE "RSDL"."AUTH_MENU_OPERATE" MODIFY ("CODE" NOT NULL ENABLE);
 
  ALTER TABLE "RSDL"."AUTH_MENU_OPERATE" MODIFY ("NAME" NOT NULL ENABLE);
 
  ALTER TABLE "RSDL"."AUTH_MENU_OPERATE" MODIFY ("MENU_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table AUTH_PERMISSION_GRANT
--------------------------------------------------------

  ALTER TABLE "RSDL"."AUTH_PERMISSION_GRANT" ADD CONSTRAINT "AUTH_PERMISSION_GRANT_FK1" FOREIGN KEY ("ROLE_ID")
	  REFERENCES "RSDL"."AUTH_ROLE" ("ROLE_ID") ENABLE;
 
  ALTER TABLE "RSDL"."AUTH_PERMISSION_GRANT" ADD CONSTRAINT "AUTH_PERMISSION_GRANT_FK2" FOREIGN KEY ("PERMISSION_ID")
	  REFERENCES "RSDL"."AUTH_PERMISSION" ("PERMISSION_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table AUTH_USER_ROLE
--------------------------------------------------------

  ALTER TABLE "RSDL"."AUTH_USER_ROLE" ADD CONSTRAINT "AUTH_USER_ROLE_FK1" FOREIGN KEY ("USER_ID")
	  REFERENCES "RSDL"."AUTH_USER" ("USER_ID") ENABLE;
 
  ALTER TABLE "RSDL"."AUTH_USER_ROLE" ADD CONSTRAINT "AUTH_USER_ROLE_FK2" FOREIGN KEY ("ROLE_ID")
	  REFERENCES "RSDL"."AUTH_ROLE" ("ROLE_ID") ENABLE;
